Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: vrising-
    SupplierDeployMetadata:
      ArtifactRelation:
        'm-2zednt7gbkyqd1u3p4my':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 快速部署
        Url: 'ros_templates/vrising.yaml'
      - Name: 迁移到计算巢
        Url: 'ros_templates/vrising-ecs.yaml'
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo_zh-CN.png
      Locale: zh-CN
      Name: 夜族崛起-快速部署
      ShortDescription: 《夜族崛起》是Stunlock Studios制作发行的一款大型多人在线的动作冒险游戏，以哥特风格的开放世界展开，玩家将扮演一名刚醒来的虚弱吸血鬼，寻找血液以恢复体力，同时躲避烈日以求生存。重建城堡和吸血鬼帝国，将人类变成忠诚的仆人。2024年5月8日，《夜族崛起》1.0完整版正式上线Steam平台。
      Softwares: []
    - Agreements: []
      Image: resources/icons/service_logo_en-US.png
      Locale: en-US
      Name: VRising-Rapid Deployment
      ShortDescription: VRising is a massively multiplayer online action-adventure game produced and released by Stunlock Studios. It is launched in a gothic-style open world. Players
        will play a weak vampire who has just woken up, looking for blood to regain his strength, while avoiding the scorching sun to survive. Rebuild castles and vampire empires and
        turn humans into loyal servants. On May 8, 2024, the 1.0 full version of "Rise of the Night Clan" was officially launched on the Steam platform.
      Softwares: []
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: VRising
    Description: VRising deploy
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: cn-hangzhou
    SourceImageId: m-bp1c22sr2g8pwpr95x71
    SystemDiskSize: 40
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 10
    CommandType: RunPowerShellScript
    Timeout: 10800
    CommandContent: |-
        # 更新游戏版本
        Start-Process "C:\Program Files\VRisingServer\steam\steamcmd.exe" -ArgumentList "+login anonymous +app_update 1829350 validate +quit" -Wait
